import { StateVisitData } from "@/types/travel";

export const visitedStates: StateVisitData[] = [
  {
    id: "IN-BR",
    name: "Bihar",
    visited: true,
    cities: [
      { name: "Motihari", visited: true, date: "2010-01-01" },
      { name: "Patna", visited: true, date: "2023-12-10" },
      { name: "Gaya", visited: true, date: "2023-12-12" },
      { name: "Nalanda", visited: true, date: "2023-12-14" },
    ],
    visitMonthYear: "01-2010",
    notes: "My home state! Visited family and explored historical sites.",
  },
  {
    id: "IN-DL",
    name: "Delhi",
    visited: true,
    cities: [{ name: "New Delhi", visited: true, date: "2022-05-15" }],
    visitMonthYear: "05-2022",
    notes: "The capital city vibes and street food.",
  },
  {
    id: "IN-HR",
    name: "Haryana",
    visited: true,
    cities: [
      { name: "Gurugram", visited: true, date: "2025-11-14" },
      { name: "Sonipat", visited: true, date: "2025-11-14" },
    ],
    visitMonthYear: "11-2025",
    notes: "Visited for organizing a tech event in Gurugram.",
  },
  {
    id: "IN-WB",
    name: "West Bengal",
    visited: true,
    cities: [{ name: "Kolkata", visited: true, date: "2023-08-15" }],
    visitMonthYear: "08-2023",
    notes: "Visited for SSB Interview.",
  },
  {
    id: "IN-MH",
    name: "Maharashtra",
    visited: true,
    cities: [
      { name: "Mumbai", visited: true, date: "2024-07-12" },
      { name: "Pune", visited: true, date: "2024-07-12" },
    ],
    visitMonthYear: "07-2024",
    notes: "Microsoft Office Visit as a Speaker",
  },
  {
    id: "IN-KA",
    name: "Karnataka",
    visited: true,
    cities: [
      { name: "Bengaluru", visited: true, date: "2024-01-12" },
      { name: "Mysuru", visited: true, date: "2024-01-12" },
    ],
    visitMonthYear: "01-2024",
    notes: "Sponsored by Govt. of India and IRCTC for Yuva Sangam",
  },
  {
    id: "IN-UP",
    name: "Uttar Pradesh",
    visited: true,
    cities: [
      { name: "Allahabad (Prayagraj)", visited: true, date: "2023-11-05" },
      { name: "Lucknow", visited: true, date: "2023-11-05" },
      { name: "Varanasi", visited: true, date: "2023-11-08" },
    ],
    visitMonthYear: "11-2023",
  },
  {
    id: "IN-CT",
    name: "Chhattisgarh",
    visited: true,
    cities: [
      { name: "Dhamtari", visited: true, date: "2025-11-27" },
      { name: "Raipur", visited: true, date: "2025-11-27" },
      { name: "Bilaspur", visited: true, date: "2025-11-27" },
    ],
    visitMonthYear: "11-2025",
    notes: "For Techstars Startup Weekend as a Top 100 Founder",
  },
  { id: "IN-RJ", name: "Rajasthan", visited: false, cities: [] },
  { id: "IN-TN", name: "Tamil Nadu", visited: false, cities: [] },
  { id: "IN-AP", name: "Andhra Pradesh", visited: false, cities: [] },
  { id: "IN-MP", name: "Madhya Pradesh", visited: false, cities: [] },
  { id: "IN-GJ", name: "Gujarat", visited: false, cities: [] },
  { id: "IN-OR", name: "Odisha", visited: false, cities: [] },
  { id: "IN-KL", name: "Kerala", visited: false, cities: [] },
  { id: "IN-JH", name: "Jharkhand", visited: false, cities: [] },
  { id: "IN-AS", name: "Assam", visited: false, cities: [] },
  { id: "IN-PB", name: "Punjab", visited: false, cities: [] },
  { id: "IN-UT", name: "Uttarakhand", visited: false, cities: [] },
  { id: "IN-HP", name: "Himachal Pradesh", visited: false, cities: [] },
  { id: "IN-JK", name: "Jammu and Kashmir", visited: false, cities: [] },
  { id: "IN-TR", name: "Tripura", visited: false, cities: [] },
  { id: "IN-ML", name: "Meghalaya", visited: false, cities: [] },
  { id: "IN-MN", name: "Manipur", visited: false, cities: [] },
  { id: "IN-NL", name: "Nagaland", visited: false, cities: [] },
  { id: "IN-GA", name: "Goa", visited: false, cities: [] },
  { id: "IN-AR", name: "Arunachal Pradesh", visited: false, cities: [] },
  { id: "IN-MZ", name: "Mizoram", visited: false, cities: [] },
  { id: "IN-SK", name: "Sikkim", visited: false, cities: [] },
];
