import { StateVisitData } from "@/types/travel";

export const visitedStates: StateVisitData[] = [
  {
    id: "IN-BR",
    name: "Bihar",
    visited: true,
    cities: [
      {
        name: "Motihari (East Champaran) - My Home",
        visited: true,
        date: "2010-01-01",
      },
      { name: "Bettiah (West Champaran)", visited: true, date: "2015-08-30" },
      { name: "Patna", visited: true, date: "2023-12-10" },
      { name: "Muzaffarpur", visited: true, date: "2023-12-10" },
      { name: "Gaya", visited: true, date: "2023-12-12" },
      { name: "Nalanda", visited: true, date: "2023-12-14" },
    ],
    visitMonthYear: "01-2010",
    notes: "My home state! Visited family and explored historical sites.",
  },
  {
    id: "IN-JH",
    name: "Jharkhand",
    visited: true,
    cities: [{ name: "Ranchi", visited: true, date: "2023-06-07" }],
    visitMonthYear: "06-2023",
  },
  {
    id: "IN-DL",
    name: "Delhi",
    visited: true,
    cities: [{ name: "New Delhi", visited: true, date: "2022-05-15" }],
    visitMonthYear: "05-2022",
    notes: "The capital city vibes and street food.",
  },
  {
    id: "IN-HR",
    name: "Haryana",
    visited: true,
    cities: [
      { name: "Gurugram", visited: true, date: "2024-09-14" },
      { name: "Sonipat", visited: true, date: "2025-11-14" },
    ],
    visitMonthYear: "09-2024",
    notes:
      "Visited at Microsoft Office, Gurugram as a Guest Speaker and at Sonipat for organizing Paranox 2.O Hackathon.",
  },
  {
    id: "IN-WB",
    name: "West Bengal",
    visited: true,
    cities: [{ name: "Kolkata", visited: true, date: "2023-08-27" }],
    visitMonthYear: "08-2023",
    notes: "Visited for Indian Navy SSB Interview at SSB, Kolkata.",
  },
  {
    id: "IN-MH",
    name: "Maharashtra",
    visited: true,
    cities: [
      { name: "Mumbai", visited: true, date: "2024-12-07" },
      { name: "Pune", visited: true, date: "2024-12-07" },
      { name: "Kurla", visited: true, date: "2024-12-06" },
    ],
    visitMonthYear: "12-2024",
    notes: "Microsoft Office, Mumbai Visit as a Speaker",
  },
  {
    id: "IN-KA",
    name: "Karnataka",
    visited: true,
    cities: [
      { name: "Bengaluru", visited: true, date: "2024-11-25" },
      { name: "Mysuru", visited: true, date: "2024-11-25" },
    ],
    visitMonthYear: "11-2024",
    notes: "Sponsored by Govt. of India and IRCTC for Yuva Sangam",
  },
  {
    id: "IN-UP",
    name: "Uttar Pradesh",
    visited: true,
    cities: [
      { name: "Allahabad (Prayagraj)", visited: true, date: "2024-01-31" },
      { name: "Lucknow", visited: true, date: "2024-11-23" },
      { name: "Varanasi", visited: true, date: "2024-11-24" },
    ],
    visitMonthYear: "01-2024",
    notes:
      "Visited Allahabad for SSB Interview at Selection Centre East, Prayagraj (Allahabad) & Lucknow and Varanasi for Yuva Sangam and cultural exploration.",
  },
  {
    id: "IN-CT",
    name: "Chhattisgarh",
    visited: true,
    cities: [
      { name: "Dhamtari", visited: true, date: "2025-11-27" },
      { name: "Raipur", visited: true, date: "2025-11-27" },
      { name: "Bilaspur", visited: true, date: "2025-11-27" },
    ],
    visitMonthYear: "11-2025",
    notes: "For Techstars Startup Weekend as a Top 100 Founder",
  },
  { id: "IN-RJ", name: "Rajasthan", visited: false, cities: [] },
  { id: "IN-TN", name: "Tamil Nadu", visited: false, cities: [] },
  { id: "IN-AP", name: "Andhra Pradesh", visited: false, cities: [] },
  { id: "IN-MP", name: "Madhya Pradesh", visited: false, cities: [] },
  { id: "IN-GJ", name: "Gujarat", visited: false, cities: [] },
  { id: "IN-OR", name: "Odisha", visited: false, cities: [] },
  { id: "IN-KL", name: "Kerala", visited: false, cities: [] },
  { id: "IN-AS", name: "Assam", visited: false, cities: [] },
  { id: "IN-PB", name: "Punjab", visited: false, cities: [] },
  { id: "IN-UT", name: "Uttarakhand", visited: false, cities: [] },
  { id: "IN-HP", name: "Himachal Pradesh", visited: false, cities: [] },
  { id: "IN-JK", name: "Jammu and Kashmir", visited: false, cities: [] },
  { id: "IN-TR", name: "Tripura", visited: false, cities: [] },
  { id: "IN-ML", name: "Meghalaya", visited: false, cities: [] },
  { id: "IN-MN", name: "Manipur", visited: false, cities: [] },
  { id: "IN-NL", name: "Nagaland", visited: false, cities: [] },
  { id: "IN-GA", name: "Goa", visited: false, cities: [] },
  { id: "IN-AR", name: "Arunachal Pradesh", visited: false, cities: [] },
  { id: "IN-MZ", name: "Mizoram", visited: false, cities: [] },
  { id: "IN-SK", name: "Sikkim", visited: false, cities: [] },
];
